### PR TITLE
fix(storybook): rename config to preview

### PR DESCRIPTION
**Pull request by andrew-secret**

### CODE REVIEW

**Comment by andrew-secret** [comment]
https://github.com/storybookjs/storybook/issues/10200#issuecomment-603120100

**Comment by HenrikFricke** [comment]
Late night programming? 🤭

**Comment by andrew-secret** [comment]
> Late night programming? 🤭

backshift 🏗🤷‍♂️

**Comment by HenrikFricke** [comment]
Good luck 🙈

**Pull request merged**
